-- ============================================================================
-- Cultural Marketplace — Supabase/Postgres schema
-- Migrated from MariaDB (DATABASE/online_marketplace.sql)
-- Conventions: identity PKs (legacy ids preserved); timestamptz everywhere;
-- enums -> text + CHECK; json-in-text -> jsonb; FKs + indexes added (dump had none).
-- ============================================================================

create extension if not exists "pgcrypto";

-- ----------------------------------------------------------------------------
-- users (unified account table: customer | artisan | admin)
-- ----------------------------------------------------------------------------
create table if not exists users (
  id              bigint generated by default as identity primary key,
  name            varchar(100) not null,
  email           varchar(100) not null unique,
  password        varchar(255) not null,             -- bcrypt ($2y / $2b) — verified by bcryptjs
  role            text not null default 'customer' check (role in ('customer','artisan','admin')),
  location        varchar(100),
  phone           varchar(30),
  otp_code        varchar(10),
  otp_expires_at  timestamptz,
  is_verified     boolean not null default false,
  profile_picture text,
  bio             text,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now(),
  reg_date        timestamptz default now()
);

-- ----------------------------------------------------------------------------
-- artisans (extended artisan profile; 1:1 with users via email in legacy data)
-- ----------------------------------------------------------------------------
create table if not exists artisans (
  id                     bigint generated by default as identity primary key,
  name                   varchar(100) not null,
  email                  varchar(100) not null unique,
  password               varchar(255) not null,
  location               varchar(100),
  business_name          varchar(100),
  craft_type             varchar(100),
  dob                    date,
  id_document_path       text,
  id_document_back_path  text,
  id_number              varchar(255) unique,
  proof_of_craft_path    text,
  product_sample_1_path  text,
  product_sample_2_path  text,
  verification_status    text not null default 'pending'
                         check (verification_status in ('pending','approved','rejected','suspended')),
  profile_picture        text,
  bio                    text,
  phone                  varchar(30),
  reg_date               timestamptz default now(),
  created_at             timestamptz default now(),
  updated_at             timestamptz default now()
);

create table if not exists customers (
  id         bigint generated by default as identity primary key,
  name       varchar(100) not null,
  email      varchar(100) not null unique,
  password   varchar(255) not null,
  location   varchar(100),
  phone      varchar(30),
  profile_picture text,
  bio        text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists admins (
  id              bigint generated by default as identity primary key,
  username        varchar(100) not null unique,
  email           varchar(100) not null unique,
  password        varchar(255) not null,
  name            varchar(100) not null default 'System Administrator',
  profile_picture text,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- ----------------------------------------------------------------------------
-- categories (shared by products and experiences)
-- ----------------------------------------------------------------------------
create table if not exists categories (
  id         bigint generated by default as identity primary key,
  name       varchar(255) not null,
  type       text not null default 'product' check (type in ('product','experience')),
  created_at timestamptz default now()
);

-- ----------------------------------------------------------------------------
-- products (physical crafts + workshops/experiences in one table, as legacy)
-- ----------------------------------------------------------------------------
create table if not exists products (
  id                          bigint generated by default as identity primary key,
  artisan_id                  bigint not null references artisans(id) on delete cascade,
  name                        varchar(150) not null,
  description                 text,
  price                       numeric(10,2) not null check (price >= 0),
  stock_quantity              integer not null default 0,
  category                    varchar(100),
  image_path                  text,
  image_2_path                text,
  image_3_path                text,
  image_4_path                text,
  product_gallery             jsonb default '[]'::jsonb,
  video_path                  text,
  status                      text not null default 'active' check (status in ('active','inactive')),
  nfc_tag_id                  varchar(100) unique,
  nfc_tag_status              text default 'active' check (nfc_tag_status in ('active','inactive','lost')),
  nfc_tag_history             jsonb,
  has_tutorial                boolean not null default false,
  tutorial_date               timestamptz,
  tutorial_price              numeric(10,2),
  tutorial_capacity           integer,
  tutorial_location           varchar(255),
  tutorial_lat                numeric(10,8),
  tutorial_lng                numeric(11,8),
  materials_used              varchar(255),
  attributes                  jsonb,
  has_variations              boolean not null default false,
  variation_pricing           boolean not null default false,
  variations_data             jsonb,
  tutorial_title              varchar(255),
  tutorial_description        text,
  tutorial_dates              jsonb,
  tutorial_time               varchar(255),
  tutorial_venue_barangay     varchar(255),
  tutorial_venue_municipality varchar(255),
  tutorial_venue_street       varchar(255),
  tutorial_venue_meeting_place varchar(255),
  tutorial_fee_type           text check (tutorial_fee_type in ('paid','free')),
  tutorial_gallery            jsonb,
  tutorial_learnings          jsonb,
  tutorial_things_to_bring    text,
  tutorial_status             text check (tutorial_status in ('accept_bookings','draft')),
  created_at                  timestamptz default now(),
  updated_at                  timestamptz default now()
);
create index if not exists idx_products_artisan   on products(artisan_id);
create index if not exists idx_products_status    on products(status);
create index if not exists idx_products_category  on products(category);

-- ----------------------------------------------------------------------------
-- cart_items
-- ----------------------------------------------------------------------------
create table if not exists cart_items (
  id               bigint generated by default as identity primary key,
  customer_id      bigint not null references users(id) on delete cascade,
  product_id       bigint not null references products(id) on delete cascade,
  purchase_type    text not null default 'product' check (purchase_type in ('product','workshop','bundle')),
  attendee_for     text default 'self' check (attendee_for in ('self','others')),
  attendee_name    varchar(191),
  attendee_contact varchar(100),
  attendee_note    text,
  selected_session jsonb,
  quantity         integer not null default 1 check (quantity > 0),
  selected_variant text,
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);
create index if not exists idx_cart_customer on cart_items(customer_id);

-- ----------------------------------------------------------------------------
-- orders + order_items
-- ----------------------------------------------------------------------------
create table if not exists orders (
  id                bigint generated by default as identity primary key,
  customer_id       bigint not null references users(id),
  total_amount      numeric(12,2) not null check (total_amount >= 0),
  status            varchar(50) not null default 'pending',
  payment_method    varchar(50) not null default 'cash_on_delivery',
  paymongo_link_id  varchar(255),
  shipping_address  text,
  notes             text,
  payment_receipt   text,
  payment_reference varchar(255),
  created_at        timestamptz default now(),
  updated_at        timestamptz default now()
);
create index if not exists idx_orders_customer on orders(customer_id);
create index if not exists idx_orders_status   on orders(status);

create table if not exists order_items (
  id                bigint generated by default as identity primary key,
  order_id          bigint not null references orders(id) on delete cascade,
  product_id        bigint not null references products(id),
  artisan_id        bigint not null references artisans(id),
  product_name      varchar(255) not null,
  purchase_type     text not null default 'product' check (purchase_type in ('product','workshop','bundle')),
  attendee_for      text default 'self' check (attendee_for in ('self','others')),
  attendee_name     varchar(191),
  attendee_contact  varchar(100),
  attendee_note     text,
  selected_session  jsonb,
  ticket_code       varchar(255) unique,
  quantity          integer not null default 1,
  price             numeric(12,2) not null,
  status            varchar(50) default 'pending',
  review_rating     integer check (review_rating between 1 and 5),
  review_comment    text,
  reviewed_at       timestamptz,
  proof_of_receipt  text,
  courier_name      varchar(100),
  tracking_number   varchar(100),
  selected_variant  varchar(255),
  created_at        timestamptz default now(),
  updated_at        timestamptz default now()
);
create index if not exists idx_order_items_order   on order_items(order_id);
create index if not exists idx_order_items_artisan on order_items(artisan_id);

create table if not exists customer_addresses (
  id          bigint generated by default as identity primary key,
  customer_id bigint not null references users(id) on delete cascade,
  label       varchar(50) default 'Home',
  full_name   varchar(100),
  phone       varchar(30),
  address     text not null,
  landmark    text,
  is_default  boolean not null default false,
  created_at  timestamptz default now()
);
create index if not exists idx_addresses_customer on customer_addresses(customer_id);

-- ----------------------------------------------------------------------------
-- chat
-- ----------------------------------------------------------------------------
create table if not exists chat_conversations (
  id              bigint generated by default as identity primary key,
  customer_id     bigint not null references users(id) on delete cascade,
  artisan_id      bigint not null references artisans(id) on delete cascade,
  product_id      bigint references products(id) on delete set null,
  last_message_at timestamptz default now(),
  created_at      timestamptz default now(),
  unique (customer_id, artisan_id, product_id)
);
create index if not exists idx_conv_artisan  on chat_conversations(artisan_id, last_message_at);
create index if not exists idx_conv_customer on chat_conversations(customer_id, last_message_at);

create table if not exists chat_messages (
  id              bigint generated by default as identity primary key,
  conversation_id bigint not null references chat_conversations(id) on delete cascade,
  sender_role     text not null check (sender_role in ('customer','artisan')),
  message         text not null,
  read_at         timestamptz,
  created_at      timestamptz default now()
);
create index if not exists idx_msg_conv_created on chat_messages(conversation_id, created_at);

-- ----------------------------------------------------------------------------
-- notifications / activity_logs / reports / settings / face_embeddings
-- ----------------------------------------------------------------------------
create table if not exists notifications (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references users(id) on delete cascade,
  user_role  varchar(50) not null,
  type       varchar(100) not null,
  message    text not null,
  data       jsonb,
  is_read    boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists idx_notif_user on notifications(user_id, user_role, is_read);

create table if not exists activity_logs (
  id          bigint generated by default as identity primary key,
  user_id     bigint,
  user_role   text not null default 'system' check (user_role in ('admin','artisan','customer','system')),
  user_name   varchar(191) not null default 'System',
  action      varchar(191) not null,
  description text not null,
  ip_address  varchar(45) not null default '',
  created_at  timestamptz default now()
);
create index if not exists idx_logs_created on activity_logs(created_at);

create table if not exists reports (
  id            bigint generated by default as identity primary key,
  reporter_id   bigint not null references users(id),
  reported_type text not null check (reported_type in ('product','artisan','experience')),
  reported_id   bigint not null,
  reason        text not null,
  status        text not null default 'pending' check (status in ('pending','investigating','resolved')),
  action_taken  text,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

create table if not exists settings (
  key   varchar(255) primary key,
  value text not null
);

create table if not exists face_embeddings (
  id          bigint generated by default as identity primary key,
  artisan_id  bigint not null references artisans(id) on delete cascade,
  embedding   jsonb not null,
  created_at  timestamptz default now()
);
create index if not exists idx_face_artisan on face_embeddings(artisan_id);

-- ----------------------------------------------------------------------------
-- updated_at triggers
-- ----------------------------------------------------------------------------
create or replace function set_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

do $$
declare t text;
begin
  foreach t in array array['users','artisans','customers','admins','products','cart_items',
                           'orders','order_items','notifications','reports','chat_conversations']
  loop
    execute format('drop trigger if exists trg_%s_updated on %I', t, t);
    execute format('create trigger trg_%s_updated before update on %I
                    for each row execute function set_updated_at()', t, t);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- pending_registrations (multi-server-safe OTP state; replaces PHP session)
-- ----------------------------------------------------------------------------
create table if not exists pending_registrations (
  email        varchar(100) primary key,
  name         varchar(100) not null,
  phone        varchar(30),
  password     varchar(255) not null,
  otp_code     varchar(10) not null,
  otp_expires  timestamptz not null,
  attempts     integer not null default 0,
  created_at   timestamptz default now()
);

-- ----------------------------------------------------------------------------
-- RLS: server uses service-role; deny-all default, anon reads only for
-- public marketplace surfaces (active products, approved artisans, categories).
-- ----------------------------------------------------------------------------
alter table users              enable row level security;
alter table products           enable row level security;
alter table categories         enable row level security;
alter table artisans           enable row level security;

create policy "public read active products" on products
  for select using (status = 'active');
create policy "public read approved artisans" on artisans
  for select using (verification_status = 'approved');
create policy "public read categories" on categories
  for select using (true);
-- users intentionally has NO anon policy (deny-all) — auth handled server-side.
