-- ============================================================================
-- 0004: Shipments — J&T-style parcel booking per order item (sender=artisan,
-- recipient=customer snapshot, package details, tracking + status lifecycle).
-- One shipment per order item (multi-artisan orders produce multiple parcels).
-- ============================================================================
create table if not exists shipments (
  id                bigint generated by default as identity primary key,
  order_item_id     bigint not null references order_items(id) on delete cascade,
  order_id          bigint not null references orders(id) on delete cascade,
  artisan_id        bigint not null references artisans(id) on delete cascade,
  customer_id       bigint not null references users(id) on delete cascade,

  -- Step 1: sender (artisan) snapshot
  sender_name       varchar(150) not null,
  sender_phone      varchar(50)  not null,
  sender_address    text         not null,

  -- Step 2: recipient (customer) snapshot
  recipient_name    varchar(150) not null,
  recipient_phone   varchar(50)  not null,
  recipient_address text         not null,

  -- Step 3: package details
  items_summary     text         not null,        -- human-readable contents
  weight_kg         numeric(6,2) not null,
  length_cm         numeric(6,1),
  width_cm          numeric(6,1),
  height_cm         numeric(6,1),
  declared_value    numeric(10,2) not null,
  notes             text,

  -- Booking result
  courier_name      varchar(100) not null default 'J&T Express',
  tracking_number   varchar(100) not null,
  status            varchar(30)  not null default 'created',  -- created|dropped_off|in_transit|delivered|cancelled
  status_history    jsonb        not null default '[]',       -- [{status, at, by}]
  created_at        timestamptz  not null default now(),
  updated_at        timestamptz  not null default now()
);

create index if not exists idx_shipments_order on shipments(order_id);
create index if not exists idx_shipments_artisan on shipments(artisan_id);
create index if not exists idx_shipments_customer on shipments(customer_id);
create unique index if not exists idx_shipments_item on shipments(order_item_id);
create unique index if not exists idx_shipments_tracking on shipments(tracking_number);

-- sync updated_at automatically
create or replace function shipments_touch_updated_at() returns trigger as $$
begin new.updated_at = now(); return new; end;
$$ language plpgsql;

drop trigger if exists trg_shipments_touch on shipments;
create trigger trg_shipments_touch before update on shipments
  for each row execute function shipments_touch_updated_at();
