-- 0006: Image moderation (handicraft-relevance enforcement).
-- 1) products.status gains 'pending_review' — a product whose media was
--    auto-flagged stays hidden from buyers until an admin approves it.
-- 2) product_media_hashes stores perceptual hashes (64-bit dHash as hex) of
--    every uploaded image so the same picture can't be reused across products
--    (spam/stolen stock photos). Unique on hash.
alter table products drop constraint if exists products_status_check;
alter table products add constraint products_status_check
  check (status in ('active','inactive','pending_review'));

create table if not exists product_media_hashes (
  id          bigint generated by default as identity primary key,
  product_id  bigint not null references products(id) on delete cascade,
  hash        varchar(16) not null unique,
  created_at  timestamptz not null default now()
);
create index if not exists idx_media_hashes_product on product_media_hashes(product_id);
